name: tdesign-projects-action
description: Only for TDesign's project management automation ci
author: TDesignOteam

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: list
  color: blue

# Define your inputs here.
inputs:
  PROJECT_TYPE:
    description: >
      `LABEL2TRIGGER`: the operation performed when the label is triggered
      `PR2TRIGGER`: the operation performed when the PR is triggered
      `ISSUE2TRIGGER`: the operation performed when the issue is triggered
  PROJECT_ID:
    description: The ID of the project to which the issue will be added.

runs:
  using: node20
  main: dist/index.js
