name: tdesign-projects-action
description: Only for TDesign's project management automation ci
author: TDesignOteam

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: list
  color: blue

# Define your inputs here.
inputs:
  PROJECT_TYPE:
    description: >
      `ISSUE2PROJECTS`: add issue to Projects;  
      `PRLINKISSUE`: the operation performed when PR is linked to issue
    required: true
    default: 'ISSUE2PROJECTS'

runs:
  using: node20
  main: dist/index.js
